// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC60GUh9rI_WhEDsMtCP7GibJ7TS09Slhw',
    appId: '1:948461763861:web:93e1b34b80a0ac2b65bd1c',
    messagingSenderId: '948461763861',
    projectId: 'pankaj-portfolio-a20fb',
    authDomain: 'pankaj-portfolio-a20fb.firebaseapp.com',
    storageBucket: 'pankaj-portfolio-a20fb.firebasestorage.app',
    measurementId: 'G-Q7HLTH8J9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBys8_alCpw2HT08Zy_kflD2uMokoaTKJw',
    appId: '1:948461763861:android:6d55e78456e4129e65bd1c',
    messagingSenderId: '948461763861',
    projectId: 'pankaj-portfolio-a20fb',
    storageBucket: 'pankaj-portfolio-a20fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUBTSOJ0mBuwZAzAKmipkYhRl8UOoYJg',
    appId: '1:948461763861:ios:f8e271bfda51258965bd1c',
    messagingSenderId: '948461763861',
    projectId: 'pankaj-portfolio-a20fb',
    storageBucket: 'pankaj-portfolio-a20fb.firebasestorage.app',
    iosBundleId: 'com.example.pankajPortfolio',
  );
}
